// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as WatermarkService from "./watermarkservice.js";
export {
    WatermarkService
};

export type {
    WatermarkResult
} from "./models.js";
