// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface WatermarkResult {
    "output_path": string;
    "base64_png": string;
}
