// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class WatermarkResult {
    /**
     * Creates a new WatermarkResult instance.
     * @param {Partial<WatermarkResult>} [$$source = {}] - The source object to create the WatermarkResult.
     */
    constructor($$source = {}) {
        if (!("output_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output_path"] = "";
        }
        if (!("base64_png" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base64_png"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WatermarkResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WatermarkResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WatermarkResult(/** @type {Partial<WatermarkResult>} */($$parsedSource));
    }
}
