// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DecodeRoomCode extracts a room code from a blind-watermarked image (base64 encoded).
 * @param {string} imageBase64
 * @returns {$CancellablePromise<string>}
 */
export function DecodeRoomCode(imageBase64) {
    return $Call.ByID(2754020915, imageBase64);
}

/**
 * EncodeRoomCode embeds a room code into a source image using blind watermarking.
 * The resulting image looks identical to the original to the naked eye.
 * @param {string} sourcePath
 * @param {string} roomCode
 * @returns {$CancellablePromise<$models.WatermarkResult | null>}
 */
export function EncodeRoomCode(sourcePath, roomCode) {
    return $Call.ByID(239701887, sourcePath, roomCode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListDemoImages returns resource identifiers for embedded demo images.
 * @returns {$CancellablePromise<string[]>}
 */
export function ListDemoImages() {
    return $Call.ByID(3334707414).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.WatermarkResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
