// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DecodeRoomCode extracts a room code from a blind-watermarked image (base64 encoded).
 */
export function DecodeRoomCode(imageBase64: string): $CancellablePromise<string> {
    return $Call.ByID(2754020915, imageBase64);
}

/**
 * EncodeRoomCode embeds a room code into a source image using blind watermarking.
 * The resulting image looks identical to the original to the naked eye.
 */
export function EncodeRoomCode(sourcePath: string, roomCode: string): $CancellablePromise<$models.WatermarkResult | null> {
    return $Call.ByID(239701887, sourcePath, roomCode);
}

/**
 * ListDemoImages returns resource identifiers for embedded demo images.
 */
export function ListDemoImages(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3334707414);
}
