// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as MicrosoftService from "./microsoft/minecraftservice.js";
import * as NaidsService from "./naids/natayarkservice.js";
export {
    MicrosoftService,
    NaidsService
};

export type {
    MinecraftUser
} from "./microsoft/models.js";

export type {
    NatayarkLoginResult,
    NatayarkUser
} from "./naids/models.js";
