// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.MinecraftUser | null>}
 */
export function GetCurrentUser() {
    return $Call.ByID(584329380).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(3250259644);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RestoreSession() {
    return $Call.ByID(2614873572);
}

/**
 * @returns {$CancellablePromise<$models.MinecraftUser | null>}
 */
export function StartLogin() {
    return $Call.ByID(1540359423).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.MinecraftUser.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
