// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class MinecraftUser {
    /**
     * Creates a new MinecraftUser instance.
     * @param {Partial<MinecraftUser>} [$$source = {}] - The source object to create the MinecraftUser.
     */
    constructor($$source = {}) {
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("uuid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uuid"] = "";
        }
        if (!("access_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["access_token"] = "";
        }
        if (!("avatar_png" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avatar_png"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MinecraftUser instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MinecraftUser}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MinecraftUser(/** @type {Partial<MinecraftUser>} */($$parsedSource));
    }
}

export class NatayarkUser {
    /**
     * Creates a new NatayarkUser instance.
     * @param {Partial<NatayarkUser>} [$$source = {}] - The source object to create the NatayarkUser.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("realname" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["realname"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("last_login" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_login"] = "";
        }
        if (!("regtime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["regtime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NatayarkUser instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NatayarkUser}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NatayarkUser(/** @type {Partial<NatayarkUser>} */($$parsedSource));
    }
}
