// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetCurrentUser(): $CancellablePromise<$models.NatayarkUser | null> {
    return $Call.ByID(3824159268);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(3138533436);
}

/**
 * RestoreSession is called at startup to reload the persisted session.
 */
export function RestoreSession(): $CancellablePromise<void> {
    return $Call.ByID(1559736164);
}

export function StartLogin(): $CancellablePromise<$models.NatayarkUser | null> {
    return $Call.ByID(3788033663);
}
