// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * EventEmitter allows services to emit events without depending on
 * Wails or CLI-specific transport mechanisms.
 * @typedef {$models.EventEmitter} EventEmitter
 */
