// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EventEmitter allows services to emit events without depending on
 * Wails or CLI-specific transport mechanisms.
 */
export type EventEmitter = any;
