// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as PaperConnectService from "./paperconnectservice.js";
export {
    PaperConnectService
};

export type {
    PCPlayerEntry,
    PaperConnectConnectionStatus,
    PaperConnectRoomStatus
} from "./models.js";
