// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PCPlayerEntry {
    /**
     * Creates a new PCPlayerEntry instance.
     * @param {Partial<PCPlayerEntry>} [$$source = {}] - The source object to create the PCPlayerEntry.
     */
    constructor($$source = {}) {
        if (!("player" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["player"] = "";
        }
        if (!("clientId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientId"] = "";
        }
        if (!("isRoomHost" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRoomHost"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PCPlayerEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PCPlayerEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PCPlayerEntry(/** @type {Partial<PCPlayerEntry>} */($$parsedSource));
    }
}

/**
 * PaperConnectConnectionStatus is the guest-side connection status.
 */
export class PaperConnectConnectionStatus {
    /**
     * Creates a new PaperConnectConnectionStatus instance.
     * @param {Partial<PaperConnectConnectionStatus>} [$$source = {}] - The source object to create the PaperConnectConnectionStatus.
     */
    constructor($$source = {}) {
        if (!("room_code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["room_code"] = "";
        }
        if (!("host_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_address"] = "";
        }
        if (!("game_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["game_port"] = 0;
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("online_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["online_count"] = 0;
        }
        if (!("players" in $$source)) {
            /**
             * @member
             * @type {PCPlayerEntry[]}
             */
            this["players"] = [];
        }
        if (!("heartbeating" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["heartbeating"] = false;
        }
        if (!("disconnect_reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["disconnect_reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaperConnectConnectionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PaperConnectConnectionStatus}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("players" in $$parsedSource) {
            $$parsedSource["players"] = $$createField5_0($$parsedSource["players"]);
        }
        return new PaperConnectConnectionStatus(/** @type {Partial<PaperConnectConnectionStatus>} */($$parsedSource));
    }
}

/**
 * PaperConnectRoomStatus is the host-side room status.
 */
export class PaperConnectRoomStatus {
    /**
     * Creates a new PaperConnectRoomStatus instance.
     * @param {Partial<PaperConnectRoomStatus>} [$$source = {}] - The source object to create the PaperConnectRoomStatus.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("game_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["game_port"] = 0;
        }
        if (!("online_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["online_count"] = 0;
        }
        if (!("players" in $$source)) {
            /**
             * @member
             * @type {PCPlayerEntry[]}
             */
            this["players"] = [];
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaperConnectRoomStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PaperConnectRoomStatus}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("players" in $$parsedSource) {
            $$parsedSource["players"] = $$createField3_0($$parsedSource["players"]);
        }
        return new PaperConnectRoomStatus(/** @type {Partial<PaperConnectRoomStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PCPlayerEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
