// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface PCPlayerEntry {
    "player": string;
    "clientId": string;
    "isRoomHost": boolean;
}

export interface PaperConnectConnectionStatus {
    "room_code": string;
    "host_address": string;
    "game_port": number;
    "sub_protocol": string;
    "connected": boolean;
    "online_count": number;
    "players": PCPlayerEntry[] | null;
    "heartbeating": boolean;
    "disconnect_reason": string;
}

export interface PaperConnectRoomStatus {
    "code": string;
    "game_port": number;
    "sub_protocol": string;
    "online_count": number;
    "players": PCPlayerEntry[] | null;
    "running": boolean;
}
