// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface PCPlayerEntry {
    "player": string;
    "clientId": string;
    "isRoomHost": boolean;
}

/**
 * PaperConnectConnectionStatus is the guest-side connection status.
 */
export interface PaperConnectConnectionStatus {
    "room_code": string;
    "host_address": string;
    "game_port": number;
    "sub_protocol": string;
    "connected": boolean;
    "online_count": number;
    "players": PCPlayerEntry[] | null;
    "heartbeating": boolean;
    "disconnect_reason": string;
}

/**
 * PaperConnectRoomStatus is the host-side room status.
 */
export interface PaperConnectRoomStatus {
    "code": string;
    "game_port": number;
    "sub_protocol": string;
    "online_count": number;
    "players": PCPlayerEntry[] | null;
    "running": boolean;
}
