// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string[]} addrs
 * @returns {$CancellablePromise<void>}
 */
export function AddPeers(addrs) {
    return $Call.ByID(83918175, addrs);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CancelJoin() {
    return $Call.ByID(3453541945);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Cleanup() {
    return $Call.ByID(3896148725);
}

/**
 * @param {string} playerName
 * @param {string} vendorPrefix
 * @returns {$CancellablePromise<$models.PaperConnectRoomStatus | null>}
 */
export function CreateRoom(playerName, vendorPrefix) {
    return $Call.ByID(2101453668, playerName, vendorPrefix).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PaperConnectConnectionStatus | null>}
 */
export function GetConnectionStatus() {
    return $Call.ByID(696866851).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PaperConnectRoomStatus | null>}
 */
export function GetRoomStatus() {
    return $Call.ByID(2260811612).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} code
 * @param {string} playerName
 * @param {string} vendorPrefix
 * @returns {$CancellablePromise<$models.PaperConnectConnectionStatus | null>}
 */
export function JoinRoom(code, playerName, vendorPrefix) {
    return $Call.ByID(3220456788, code, playerName, vendorPrefix).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function LeaveRoom() {
    return $Call.ByID(1631908205);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopRoom() {
    return $Call.ByID(3622720108);
}

// Private type creation functions
const $$createType0 = $models.PaperConnectRoomStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.PaperConnectConnectionStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
