// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface LanServer {
    "motd": string;
    "ip": string;
    "port": number;
}
