// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetCurrentUser(): $CancellablePromise<$models.MinecraftUser | null> {
    return $Call.ByID(584329380);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(3250259644);
}

export function RestoreSession(): $CancellablePromise<void> {
    return $Call.ByID(2614873572);
}

export function StartLogin(): $CancellablePromise<$models.MinecraftUser | null> {
    return $Call.ByID(1540359423);
}
