// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface MinecraftUser {
    "username": string;
    "uuid": string;
    "access_token": string;
    "avatar_png": string;
}
