//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as easytier$0 from "../../../../../gravitycone/core/easytier/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as minecraft$0 from "../../../../../gravitycone/core/minecraft/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scaffolding$0 from "../../../../../gravitycone/core/protocol/scaffolding/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "download.error": $$createType0,
        "download.progress": $$createType1,
        "lan.server_found": $$createType2,
        "lan.server_lost": $$createType3,
        "room.closed": $$createType4,
        "room.disconnected": $$createType4,
        "room.guest_player_list_updated": $$createType6,
        "room.player_joined": $$createType5,
        "room.player_left": $$createType5,
    }));
}

// Private type creation functions
const $$createType0 = easytier$0.DownloadErrorData.createFrom;
const $$createType1 = easytier$0.DownloadProgressData.createFrom;
const $$createType2 = minecraft$0.LanServer.createFrom;
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = scaffolding$0.PlayerInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);

configure();
