// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateRoom(ip: string, port: number): $CancellablePromise<void> {
    return $Call.ByID(1192140046, ip, port);
}

export function GetDiscoveredServers(): $CancellablePromise<$models.LanServer[] | null> {
    return $Call.ByID(1608312239);
}

export function StartDiscovery(): $CancellablePromise<void> {
    return $Call.ByID(4289422875);
}

export function StopDiscovery(): $CancellablePromise<void> {
    return $Call.ByID(789088201);
}

export function VerifyServer(ip: string, port: number): $CancellablePromise<string> {
    return $Call.ByID(2805999667, ip, port);
}
