// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelJoin aborts a running JoinRoom call. Safe to call even if no join is in progress.
 */
export function CancelJoin(): $CancellablePromise<void> {
    return $Call.ByID(3960731962);
}

/**
 * Cleanup stops any running room or connection (called on app shutdown)
 */
export function Cleanup(): $CancellablePromise<void> {
    return $Call.ByID(3318415232);
}

export function CreateRoom(mcPort: number, playerName: string): $CancellablePromise<$models.RoomStatus | null> {
    return $Call.ByID(2616414379, mcPort, playerName);
}

export function GetConnectionStatus(): $CancellablePromise<$models.ConnectionStatus | null> {
    return $Call.ByID(2919172306);
}

export function GetRoomStatus(): $CancellablePromise<$models.RoomStatus | null> {
    return $Call.ByID(969092125);
}

export function JoinRoom(code: string, playerName: string): $CancellablePromise<$models.ConnectionStatus | null> {
    return $Call.ByID(3330044535, code, playerName);
}

export function LeaveRoom(): $CancellablePromise<void> {
    return $Call.ByID(847243300);
}

export function StopRoom(): $CancellablePromise<void> {
    return $Call.ByID(1930853247);
}
