// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetCurrentUser(): $CancellablePromise<$models.MinecraftUser | null> {
    return $Call.ByID(1314052116);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(1702342572);
}

export function RestoreSession(): $CancellablePromise<void> {
    return $Call.ByID(221513524);
}

export function StartLogin(): $CancellablePromise<$models.MinecraftUser | null> {
    return $Call.ByID(221955759);
}
