// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ConnectionStatus {
    "room_code": string;
    "host_address": string;
    "mc_address": string;
    "mc_port": number;
    "connected": boolean;
    "online_count": number;
    "players": PlayerInfo[] | null;
    "heartbeating": boolean;
    "disconnect_reason": string;
}

/**
 * DownloadProgressData is the data shape emitted during download progress events.
 */
export interface DownloadProgressData {
    /**
     * "downloading" or "extracting"
     */
    "step": string;

    /**
     * 0-100
     */
    "percent": number;

    /**
     * total bytes (0 if unknown)
     */
    "total_size": number;

    /**
     * bytes/sec (download step only)
     */
    "speed": number;
}

export interface LanServer {
    "motd": string;
    "ip": string;
    "port": number;
}

export interface MinecraftUser {
    "username": string;
    "uuid": string;
    "access_token": string;
    "avatar_png": string;
}

export interface NatayarkUser {
    "id": number;
    "username": string;
    "email": string;
    "realname": boolean;
    "status": number;
    "last_login": string;
    "regtime": string;
}

export interface PlayerInfo {
    "name": string;
    "machine_id": string;
    "easytier_id"?: string;
    "vendor": string;

    /**
     * "HOST" or "GUEST"
     */
    "kind": string;
}

export interface RoomStatus {
    "code": string;
    "mc_address": string;
    "mc_port": number;
    "online_count": number;
    "players": PlayerInfo[] | null;
    "running": boolean;
}

export interface StunResult {
    "udp_nat_type": number;
    "tcp_nat_type": number;
    "last_update_time": number;
    "public_ip": string[] | null;
    "min_port": number;
    "max_port": number;
}

export interface WatermarkResult {
    "output_path": string;
    "base64_png": string;
}
