// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ConnectionStatus {
    "room_code": string;
    "host_address": string;
    "mc_address": string;
    "mc_port": number;
    "connected": boolean;
    "online_count": number;
    "players": PlayerInfo[] | null;
    "heartbeating": boolean;
    "disconnect_reason": string;
}

export interface LanServer {
    "motd": string;
    "ip": string;
    "port": number;
}

export interface NatayarkUser {
    "id": number;
    "username": string;
    "email": string;
    "realname": boolean;
    "status": number;
    "last_login": string;
    "regtime": string;
}

export interface PCPlayerEntry {
    "player": string;
    "clientId": string;
    "isRoomHost": boolean;
}

/**
 * PaperConnectConnectionStatus is the guest-side connection status.
 */
export interface PaperConnectConnectionStatus {
    "room_code": string;
    "host_address": string;
    "game_port": number;
    "connected": boolean;
    "online_count": number;
    "players": PCPlayerEntry[] | null;
    "heartbeating": boolean;
    "disconnect_reason": string;
}

/**
 * PaperConnectRoomStatus is the host-side room status.
 */
export interface PaperConnectRoomStatus {
    "code": string;
    "game_port": number;
    "online_count": number;
    "players": PCPlayerEntry[] | null;
    "running": boolean;
}

export interface PlayerInfo {
    "name": string;
    "machine_id": string;
    "easytier_id"?: string;
    "vendor": string;

    /**
     * "HOST" or "GUEST"
     */
    "kind": string;
}

export interface RoomStatus {
    "code": string;
    "mc_address": string;
    "mc_port": number;
    "online_count": number;
    "players": PlayerInfo[] | null;
    "running": boolean;
}

export interface StunResult {
    "udp_nat_type": number;
    "tcp_nat_type": number;
    "last_update_time": number;
    "public_ip": string[] | null;
    "min_port": number;
    "max_port": number;
}

export interface WatermarkResult {
    "output_path": string;
    "base64_png": string;
}
