// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddPeers(addrs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2028729157, addrs);
}

export function CancelJoin(): $CancellablePromise<void> {
    return $Call.ByID(4286668103);
}

export function Cleanup(): $CancellablePromise<void> {
    return $Call.ByID(3703900511);
}

export function CreateRoom(playerName: string, vendorPrefix: string): $CancellablePromise<$models.PaperConnectRoomStatus | null> {
    return $Call.ByID(2516405574, playerName, vendorPrefix);
}

export function GetConnectionStatus(): $CancellablePromise<$models.PaperConnectConnectionStatus | null> {
    return $Call.ByID(2317443181);
}

export function GetRoomStatus(): $CancellablePromise<$models.PaperConnectRoomStatus | null> {
    return $Call.ByID(3829863222);
}

export function JoinRoom(code: string, playerName: string, vendorPrefix: string): $CancellablePromise<$models.PaperConnectConnectionStatus | null> {
    return $Call.ByID(3973105074, code, playerName, vendorPrefix);
}

export function LeaveRoom(): $CancellablePromise<void> {
    return $Call.ByID(4010632487);
}

export function StopRoom(): $CancellablePromise<void> {
    return $Call.ByID(3121406246);
}
