// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddPeers appends peer addresses so they are included when EasyTier starts.
 */
export function AddPeers(addrs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(111594907, addrs);
}

/**
 * CancelJoin aborts a running JoinRoom call. Safe to call even if no join is in progress.
 */
export function CancelJoin(): $CancellablePromise<void> {
    return $Call.ByID(1094851085);
}

/**
 * Cleanup stops any running room or connection (called on app shutdown)
 */
export function Cleanup(): $CancellablePromise<void> {
    return $Call.ByID(2877413657);
}

export function CreateRoom(mcPort: number, playerName: string, vendorPrefix: string, motd: string): $CancellablePromise<$models.RoomStatus | null> {
    return $Call.ByID(668317184, mcPort, playerName, vendorPrefix, motd);
}

export function GetConnectionStatus(): $CancellablePromise<$models.ConnectionStatus | null> {
    return $Call.ByID(1169126479);
}

export function GetRoomStatus(): $CancellablePromise<$models.RoomStatus | null> {
    return $Call.ByID(3873649912);
}

export function JoinRoom(code: string, playerName: string, vendorPrefix: string, motd: string): $CancellablePromise<$models.ConnectionStatus | null> {
    return $Call.ByID(1312253032, code, playerName, vendorPrefix, motd);
}

export function LeaveRoom(): $CancellablePromise<void> {
    return $Call.ByID(3396570265);
}

export function StopRoom(): $CancellablePromise<void> {
    return $Call.ByID(695010240);
}
