// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as NatayarkService from "./natayarkservice.js";
export {
    NatayarkService
};

export type {
    NatayarkLoginResult,
    NatayarkUser
} from "./models.js";
