// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface NatayarkLoginResult {
    "user": NatayarkUser | null;
    "access_token": string;
}

export interface NatayarkUser {
    "id": number;
    "username": string;
    "email": string;
    "realname": boolean;
    "status": number;
    "last_login": string;
    "regtime": string;
}
