// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetCurrentUser(): $CancellablePromise<$models.NatayarkUser | null> {
    return $Call.ByID(4147405986);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(5156266);
}

export function RestoreSession(token: string): $CancellablePromise<$models.NatayarkUser | null> {
    return $Call.ByID(3628339378, token);
}

export function StartLogin(): $CancellablePromise<$models.NatayarkLoginResult | null> {
    return $Call.ByID(4285122485);
}
