// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadErrorData is emitted when the EasyTier download fails.
 */
export interface DownloadErrorData {
    "error": string;
}

/**
 * DownloadProgressData is the data shape emitted during download progress events.
 */
export interface DownloadProgressData {
    "step": string;
    "percent": number;
    "total_size": number;
    "speed": number;
}

export interface StunResult {
    "udp_nat_type": number;
    "tcp_nat_type": number;
    "last_update_time": number;
    "public_ip": string[] | null;
    "min_port": number;
    "max_port": number;
}
