// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DownloadErrorData is emitted when the EasyTier download fails.
 */
export class DownloadErrorData {
    /**
     * Creates a new DownloadErrorData instance.
     * @param {Partial<DownloadErrorData>} [$$source = {}] - The source object to create the DownloadErrorData.
     */
    constructor($$source = {}) {
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadErrorData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadErrorData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadErrorData(/** @type {Partial<DownloadErrorData>} */($$parsedSource));
    }
}

/**
 * DownloadProgressData is the data shape emitted during download progress events.
 */
export class DownloadProgressData {
    /**
     * Creates a new DownloadProgressData instance.
     * @param {Partial<DownloadProgressData>} [$$source = {}] - The source object to create the DownloadProgressData.
     */
    constructor($$source = {}) {
        if (!("step" in $$source)) {
            /**
             * "downloading" or "extracting"
             * @member
             * @type {string}
             */
            this["step"] = "";
        }
        if (!("percent" in $$source)) {
            /**
             * 0-100
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }
        if (!("total_size" in $$source)) {
            /**
             * total bytes (0 if unknown)
             * @member
             * @type {number}
             */
            this["total_size"] = 0;
        }
        if (!("speed" in $$source)) {
            /**
             * bytes/sec (download step only)
             * @member
             * @type {number}
             */
            this["speed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadProgressData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadProgressData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadProgressData(/** @type {Partial<DownloadProgressData>} */($$parsedSource));
    }
}

export class StunResult {
    /**
     * Creates a new StunResult instance.
     * @param {Partial<StunResult>} [$$source = {}] - The source object to create the StunResult.
     */
    constructor($$source = {}) {
        if (!("udp_nat_type" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["udp_nat_type"] = 0;
        }
        if (!("tcp_nat_type" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tcp_nat_type"] = 0;
        }
        if (!("last_update_time" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_update_time"] = 0;
        }
        if (!("public_ip" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["public_ip"] = [];
        }
        if (!("min_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["min_port"] = 0;
        }
        if (!("max_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StunResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StunResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("public_ip" in $$parsedSource) {
            $$parsedSource["public_ip"] = $$createField3_0($$parsedSource["public_ip"]);
        }
        return new StunResult(/** @type {Partial<StunResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
