// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DownloadErrorData {
    "error": string;
}

export interface DownloadProgressData {
    "step": string;
    "percent": number;
    "total_size": number;
    "speed": number;
}

/**
 * StunResult 是 NAT 探测结果，桌面由 easytier-cli stun 输出，Android 由
 * FFI 的 collect_network_infos 提供（proto NatType 整数，编号与桌面一致）。
 */
export interface StunResult {
    "udp_nat_type": number;
    "tcp_nat_type": number;
    "last_update_time": number;
    "public_ip": string[] | null;
    "min_port": number;
    "max_port": number;
}
