// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function GetCustomPeers(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1307178693);
}

export function GetPublicPeers(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1351421367);
}

export function SetCustomPeers(peers: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(91832177, peers);
}
