// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as LanService from "./lanservice.js";
export {
    LanService
};

export type {
    LanServer
} from "./models.js";
