// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as utils$0 from "../utils/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.LanServer[]>}
 */
export function GetDiscoveredServers() {
    return $Call.ByID(384771432).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {utils$0.EventEmitter} emitter
 * @returns {$CancellablePromise<void>}
 */
export function SetEventEmitter(emitter) {
    return $Call.ByID(1309808372, emitter);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartDiscovery() {
    return $Call.ByID(3810941764);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopDiscovery() {
    return $Call.ByID(44299972);
}

/**
 * @param {string} ip
 * @param {number} port
 * @returns {$CancellablePromise<string>}
 */
export function VerifyServer(ip, port) {
    return $Call.ByID(3900159792, ip, port);
}

// Private type creation functions
const $$createType0 = $models.LanServer.createFrom;
const $$createType1 = $Create.Array($$createType0);
