// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LanServer {
    /**
     * Creates a new LanServer instance.
     * @param {Partial<LanServer>} [$$source = {}] - The source object to create the LanServer.
     */
    constructor($$source = {}) {
        if (!("motd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["motd"] = "";
        }
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanServer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LanServer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LanServer(/** @type {Partial<LanServer>} */($$parsedSource));
    }
}
