// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as utils$0 from "../utils/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetDiscoveredServers(): $CancellablePromise<$models.LanServer[] | null> {
    return $Call.ByID(384771432);
}

export function SetEventEmitter(emitter: utils$0.EventEmitter): $CancellablePromise<void> {
    return $Call.ByID(1309808372, emitter);
}

export function StartDiscovery(): $CancellablePromise<void> {
    return $Call.ByID(3810941764);
}

export function StopDiscovery(): $CancellablePromise<void> {
    return $Call.ByID(44299972);
}

export function VerifyServer(ip: string, port: number): $CancellablePromise<string> {
    return $Call.ByID(3900159792, ip, port);
}
