// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ConnectionStatus {
    /**
     * Creates a new ConnectionStatus instance.
     * @param {Partial<ConnectionStatus>} [$$source = {}] - The source object to create the ConnectionStatus.
     */
    constructor($$source = {}) {
        if (!("room_code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["room_code"] = "";
        }
        if (!("host_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host_address"] = "";
        }
        if (!("mc_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mc_address"] = "";
        }
        if (!("mc_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mc_port"] = 0;
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("online_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["online_count"] = 0;
        }
        if (!("players" in $$source)) {
            /**
             * @member
             * @type {PlayerInfo[]}
             */
            this["players"] = [];
        }
        if (!("heartbeating" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["heartbeating"] = false;
        }
        if (!("disconnect_reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["disconnect_reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionStatus}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("players" in $$parsedSource) {
            $$parsedSource["players"] = $$createField6_0($$parsedSource["players"]);
        }
        return new ConnectionStatus(/** @type {Partial<ConnectionStatus>} */($$parsedSource));
    }
}

export class PlayerInfo {
    /**
     * Creates a new PlayerInfo instance.
     * @param {Partial<PlayerInfo>} [$$source = {}] - The source object to create the PlayerInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("machine_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["machine_id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["easytier_id"] = undefined;
        }
        if (!("vendor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vendor"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * "HOST" or "GUEST"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayerInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayerInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayerInfo(/** @type {Partial<PlayerInfo>} */($$parsedSource));
    }
}

export class RoomStatus {
    /**
     * Creates a new RoomStatus instance.
     * @param {Partial<RoomStatus>} [$$source = {}] - The source object to create the RoomStatus.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("mc_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mc_address"] = "";
        }
        if (!("mc_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mc_port"] = 0;
        }
        if (!("online_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["online_count"] = 0;
        }
        if (!("players" in $$source)) {
            /**
             * @member
             * @type {PlayerInfo[]}
             */
            this["players"] = [];
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoomStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RoomStatus}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("players" in $$parsedSource) {
            $$parsedSource["players"] = $$createField4_0($$parsedSource["players"]);
        }
        return new RoomStatus(/** @type {Partial<RoomStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PlayerInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
