// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ConnectionStatus {
    "room_code": string;
    "host_address": string;
    "mc_address": string;
    "mc_port": number;
    "connected": boolean;
    "online_count": number;
    "players": PlayerInfo[] | null;
    "heartbeating": boolean;
    "disconnect_reason": string;
}

export interface PlayerInfo {
    "name": string;
    "machine_id": string;
    "easytier_id"?: string;
    "vendor": string;
    "kind": PlayerKind;
}

export enum PlayerKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindHost = "HOST",
    KindGuest = "GUEST",
};

export interface RoomStatus {
    "code": string;
    "mc_address": string;
    "mc_port": number;
    "online_count": number;
    "players": PlayerInfo[] | null;
    "running": boolean;
}
