// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ConnectionStatus {
    "room_code": string;
    "host_address": string;
    "mc_address": string;
    "mc_port": number;
    "connected": boolean;
    "online_count": number;
    "players": PlayerInfo[] | null;
    "heartbeating": boolean;
    "disconnect_reason": string;
}

export interface PlayerInfo {
    "name": string;
    "machine_id": string;
    "easytier_id"?: string;
    "vendor": string;

    /**
     * "HOST" or "GUEST"
     */
    "kind": string;
}

export interface RoomStatus {
    "code": string;
    "mc_address": string;
    "mc_port": number;
    "online_count": number;
    "players": PlayerInfo[] | null;
    "running": boolean;
}
