// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddPeers appends peer addresses so they are included when EasyTier starts.
 * @param {string[]} addrs
 * @returns {$CancellablePromise<void>}
 */
export function AddPeers(addrs) {
    return $Call.ByID(261516947, addrs);
}

/**
 * CancelJoin aborts a running JoinRoom call. Safe to call even if no join is in progress.
 * @returns {$CancellablePromise<void>}
 */
export function CancelJoin() {
    return $Call.ByID(455884165);
}

/**
 * Cleanup stops any running room or connection (called on app shutdown)
 * @returns {$CancellablePromise<void>}
 */
export function Cleanup() {
    return $Call.ByID(4022543137);
}

/**
 * @param {number} mcPort
 * @param {string} playerName
 * @param {string} vendorPrefix
 * @param {string} motd
 * @returns {$CancellablePromise<$models.RoomStatus | null>}
 */
export function CreateRoom(mcPort, playerName, vendorPrefix, motd) {
    return $Call.ByID(2148368552, mcPort, playerName, vendorPrefix, motd).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ConnectionStatus | null>}
 */
export function GetConnectionStatus() {
    return $Call.ByID(489009207).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RoomStatus | null>}
 */
export function GetRoomStatus() {
    return $Call.ByID(2796168464).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} code
 * @param {string} playerName
 * @param {string} vendorPrefix
 * @param {string} motd
 * @returns {$CancellablePromise<$models.ConnectionStatus | null>}
 */
export function JoinRoom(code, playerName, vendorPrefix, motd) {
    return $Call.ByID(2051558256, code, playerName, vendorPrefix, motd).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function LeaveRoom() {
    return $Call.ByID(619442881);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopRoom() {
    return $Call.ByID(2325174264);
}

// Private type creation functions
const $$createType0 = $models.RoomStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ConnectionStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
